### ISSUE TITLE
更新速度过快被阻止

### ISSUE THREAD

**Issue by 362516282** [stevenyomi/copymanga#10]
今天刚刚出现的问题，，更新速度过快会被封禁45秒。希望向部分官方插件加入限制更新速度的选项
![Screenshot_20220805_045603_com android htmlviewer](https://user-images.githubusercontent.com/36665073/182951921-701dacb5-167d-4e87-93d3-a1099c72358b.jpg)

**Comment by stevenyomi** [comment]
已更新 v1.3.39。
