### ISSUE TITLE
Tachidesk-Server上使用的问题

### ISSUE THREAD

**Issue by Mister-album** [stevenyomi/copymanga#12]
有办法在Tachidesk-Server上使用这个插件么？插件的格式是jar的，不知道与app端通不通用

**Comment by stevenyomi** [comment]
实测可以安装但无法正常使用。没有研究适配的计划。

**Comment by chris7395328** [comment]
> 实测可以安装但无法正常使用。没有研究适配的计划。

试了现在版本是可以打开首页的，就是进不了目录，问了tachidesk那边说是很愿意做适配但是没有你的源码所以没办法。
