### ISSUE TITLE
拷贝漫画最近更新不及时

### ISSUE THREAD

**Issue by pk12000** [stevenyomi/copymanga#14]
从tachi yomi最近更新点进去只更新了一部分，很多在web里才能看到

**Comment by pk12000** [comment]
就是最近更新里的不全，很多要在web里才能看到更新

**Comment by stevenyomi** [comment]
无法复现。请按照 https://github.com/stevenyomi/copymanga/issues/13#issuecomment-1217830099 检查。如果还是不行，请提供作品名称和对比截图。

**Comment by pk12000** [comment]
第一张图是我tach里最新刷出来的更新，第二张图是web的更新，tach里左上角《半分的约定》显示是最新更新的漫画，但web里能看到还有其他漫画更新了但tach里没显示出来
![Screenshot_2022-08-20-11-54-26-68_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/111525240/185728143-6fa02d77-9cdd-4ddb-b884-edeb402f0277.jpg)
![Screenshot_2022-08-20-11-55-15-69_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/111525240/185728150-5e184983-98ad-4a48-9daf-c712bd74f764.jpg)

**Comment by pk12000** [comment]
我的设置
![Screenshot_2022-08-20-12-02-47-14_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/111525240/185728186-4c49c79a-6bfb-4c40-ae62-96467ecedeba.jpg)

**Comment by stevenyomi** [comment]
“最近更新”对应的是主页面里面的“全新上架”板块。你想要的那个页面可以通过正常进入图源，然后用右下角的筛选工具来选择。

**Comment by pk12000** [comment]
问题解决了，感谢感谢
