### ISSUE TITLE
最新章节无法阅读下载

### ISSUE THREAD

**Issue by grasssand** [stevenyomi/copymanga#15]
昨天更新漫画时发现的问题，扩展更新最新

不清楚是不是个例，只有104话无法阅读，103以前都正常。修改过 ua 无效

还有最近几天检查更新时会将部分已读章节重置为未读新章节，如图3没有截全底下还有很多

![Screenshot_2022-08-20-20-27-59-483_eu kanade tachiyomi](https://user-images.githubusercontent.com/11460505/185746355-f42fe73e-aa0b-4093-a8d0-6793f9354a64.jpg)
![Screenshot_2022-08-20-20-29-42-507_eu kanade tachiyomi](https://user-images.githubusercontent.com/11460505/185746396-99e9a381-2a8a-4714-b643-33eb5f943ec1.jpg)
![Screenshot_2022-08-20-20-28-16-241_eu kanade tachiyomi](https://user-images.githubusercontent.com/11460505/185746626-ab9d383d-023f-42a4-96e0-bf821446aacd.jpg)

**Comment by stevenyomi** [comment]
已更新 v1.3.42 修复。

关于重置为未读章节，这个我也感觉很奇怪，一般是图源站修改了章节的内部 ID 并且章节名里面的编号没有识别成功（没有标号），两者同时满足才会出现。最好检查一下 app 是不是最新版。如果之后还有发生，可以反馈一下，我尝试研究一下是 app 的问题还是图源的问题。

**Comment by grasssand** [comment]
没问题了 感谢
