### ISSUE TITLE
1.3.44的apk被Windows Defender认定为威胁

### ISSUE THREAD

**Issue by FixingGoodman** [stevenyomi/copymanga#17]
威胁详情: 
Trojan:Script/Wacatac.H!ml

**Comment by stevenyomi** [comment]
https://www.virustotal.com/gui/file/5ecdc61004074e6b63ce3c478b4191a1c0cc03a6f0f56e528fd0a20f9db815b9

有人测了，并没有问题，建议跟这个链接比较一下文件校验码。
