### ISSUE TITLE
部分章节无法加载页面

### ISSUE THREAD

**Issue by AzureGu** [stevenyomi/copymanga#18]
能够在浏览器模式看到内容，但是在tachiyomi中无法加载页面，漫画名 孤独摇滚 第一次出现这种情况。
前两章可以正常加载 从第2章到第39章都显示无法加载 从第40章恢复正常
![Screenshot_2022-10-10-12-03-36-764_eu kanade tachiyomi](https://user-images.githubusercontent.com/96013345/194797963-4f40f8fb-a7f7-4fdd-827c-ab6aeee2d3e1.png)
![Screenshot_2022-10-10-12-02-10-274_eu kanade tachiyomi](https://user-images.githubusercontent.com/96013345/194797978-894faf99-9ba5-42d6-8262-aa5e8ee0a318.png)

**Comment by RX93CN** [comment]
除了孤独摇滚，拷贝漫画插件上一部分短篇和老漫画都无法加载，例如死亡进化、Origin-源型機和Re-take等，在使用拷贝漫画软件打开时一切正常，唯独tachiyomi上有无法加载的情况，更换API及调整刷新也无法加载图片

**Comment by RX93CN** [comment]
更正，现在发现插件上有许多漫画出现章节无法加载，少部分是全部无法加载，大部分是只能加载部分章节

**Comment by stevenyomi** [comment]
测试了一下，把图片分辨率调回 800 应该就可以了，我之后再看看怎么自动调整。

**Comment by AzureGu** [comment]
确实解决了 希望快整自动调整吧 让大🔥看800像素这图标级别超高糊画质是吧😡

**Comment by stevenyomi** [comment]
仔细检查了一下，是图片链接格式变化导致的，明天就更新修复。

**Comment by stevenyomi** [comment]
已更新 v1.3.45。
