### ISSUE TITLE
关于网页端被隐藏的漫画

### ISSUE THREAD

**Issue by Sodaly1318** [stevenyomi/copymanga#20]
最近发现以前收藏的漫画，有些报“漫画未找到”，如《相合之物》和《古见同学》，去拷贝网页上搜也没有找到，但是在拷贝的app端且登录账号的情况下可以搜索到并能正常观看，想问一下大佬对于这种被隐藏的漫画有没有什么解决方案

网页端搜索情况
![01](https://user-images.githubusercontent.com/101317586/197540882-0d257c47-3341-4c27-95dd-bbca2787dca9.png)
app端未登录时的搜索情况
![02](https://user-images.githubusercontent.com/101317586/197541141-408a0039-7b73-4e20-8e71-91e90dbd2654.png)
app端登录时的搜索情况
![03](https://user-images.githubusercontent.com/101317586/197541239-0c785389-48d2-4ae5-b1a7-ef2208ee63c8.png)

**Comment by stevenyomi** [comment]
这个已知，之后有空会写登录功能。

**Comment by Sodaly1318** [comment]
好的，感谢大佬🙏

**Comment by stevenyomi** [comment]
已更新 v1.3.47。
