### ISSUE TITLE
HTTP error 502

### ISSUE THREAD

**Issue by RX93CN** [stevenyomi/copymanga#21]
最近几天频繁出现502
![Screenshot_2022-11-02-10-24-01-799_eu kanade tachiyomi](https://user-images.githubusercontent.com/110704357/199381131-9443de09-1b03-4267-8424-8ec57c00a824.jpg)
是大陆网络又进行网禁了，还是什么其他原因？

**Comment by stevenyomi** [comment]
目前看下来基本是服务器的原因，没有什么其他解决办法，更换代理节点的帮助可能也有限。之后可能尝试优化限流模式和网络请求参数。

**Comment by RX93CN** [comment]
辛苦了，大佬
