### ISSUE TITLE
请求被限制

### ISSUE THREAD

**Issue by AzureGu** [stevenyomi/copymanga#22]
今天才出现的问题 更新会出现! Request was throttled. Expected available in xxx seconds.错误
![Screenshot_2022-11-27-06-04-42-214_com android htmlviewer](https://user-images.githubusercontent.com/96013345/204110658-637b28b4-1877-43ed-91b8-d5b837215735.png)
![Screenshot_2022-11-27-06-04-46-254_com android htmlviewer](https://user-images.githubusercontent.com/96013345/204110659-daf7ae07-f987-4d02-bc45-be814a58757c.png)

**Comment by stevenyomi** [comment]
在设置里把章节目录限流调到 15 以下。
