### ISSUE TITLE
可以添加tachidesk的支持吗？

### ISSUE THREAD

**Issue by MrPinku** [stevenyomi/copymanga#23]
跟踪: https://github.com/Suwayomi/Tachidesk-Server/issues/512

已在下载页上传 Tachidesk 兼容版插件，删除了“繁体转简体”、“登录状态下搜索”、“章末吐槽页”功能。

---

![image](https://user-images.githubusercontent.com/79267206/206757355-52d3bfb2-69f4-4d1b-ac27-0c6fd0fb2ac2.png)
![image](https://user-images.githubusercontent.com/79267206/206757415-334a8faf-ca3d-49c2-a398-7a8ecada0a0c.png)
进不去setting，配置不了插件所以用不了。

**Comment by misaka10843** [comment]
作者说还没有适配的计划 #12

**Comment by MrPinku** [comment]
> 作者说还没有适配的计划 #12

明白

**Comment by chris7395328** [comment]
试了现在版本是可以打开首页的，就是进不了目录，问了tachidesk那边说是很愿意做适配但是没有插件源码所以没办法。

**Comment by Mister-album** [comment]
同再次求适配，手机上存不了那么多漫画，改换tachidesk了，但没有拷贝的源就比较难受

**Comment by spirytuslove** [comment]
同求适配 现在拷贝在tachidesk里面首页点进去是黑的什么都没有 可以进入拷贝的设置界面

**Comment by misaka10843** [comment]
> 试了现在版本是可以打开首页的，就是进不了目录，问了tachidesk那边说是很愿意做适配但是没有插件源码所以没办法。

源码其实可以翻一下22年6月之前的源码，比如6.28的代码https://github.com/tachiyomiorg/tachiyomi-extensions/tree/69fa5b4571b021f32f8f22e61d4ce47e5a1e4756/src/zh/copymanga

但是因为时间比较远了，而且因为被copymanga那边的说明删除后闭源的代码就不知道了

**Comment by Mister-album** [comment]
前几天试了个骚操作，
先备份Tachiyomi的配置，然后再tachidesk这边还原配置，订阅的漫画可以看也可以正常更新，目前问题只是打不开首页
算是能平稳从Tachiyomi过度过来吧

**Comment by miyukisakurai** [comment]
> 前几天试了个骚操作， 先备份Tachiyomi的配置，然后再tachidesk这边还原配置，订阅的漫画可以看也可以正常更新，目前问题只是打不开首页 算是能平稳从Tachiyomi过度过来吧

我这样干了好久了，就是不能用搜索功能，要看新的只能去同步存档，而且有很多封面图获取不到

**Comment by zhongfly** [comment]
具体要做什么适配？我自己维护了一个插件版本，欢迎有人能提pr加上适配，我自己没能力做
https://github.com/zhongfly/tachiyomi-extensions/tree/copymangas/src/zh/copymangas (为避免被关注，几天后删除此处链接)

**Comment by 2Loong6** [comment]
其实不需要适配，只是自动安装并不会安装附属包体，只需要安装chinese-utils就可以

**Comment by spirytuslove** [comment]
> 其实不需要适配，只是自动安装并不会安装附属包体，只需要安装chinese-utils就可以

具体要怎么操作啊

**Comment by 2Loong6** [comment]
> > 其实不需要适配，只是自动安装并不会安装附属包体，只需要安装chinese-utils就可以
> 
> 具体要怎么操作啊

把chinese-utils-1.0.jar移动到tachidesk安装目录下的jre\lib\ext里就可以

**Comment by spirytuslove** [comment]
> chinese-utils-1.0.jar

chinese-utils-1.0.jar这个要在哪里下载。。。

**Comment by ouovouo** [comment]
> > chinese-utils-1.0.jar
> 
> chinese-utils-1.0.jar这个要在哪里下载。。。

https://mvnrepository.com/artifact/com.luhuiguo/chinese-utils/1.0

**Comment by spirytuslove** [comment]
> > > 其实不需要适配，只是自动安装并不会安装附属包体，只需要安装chinese-utils就可以
> > 
> > 
> > 具体要怎么操作啊
> 
> 把chinese-utils-1.0.jar移动到tachidesk安装目录下的jre\lib\ext里就可以

我是docker安装的tachidesk 好像没找到你说的安装目录。。。

**Comment by misaka10843** [comment]
> > > > 其实不需要适配，只是自动安装并不会安装附属包体，只需要安装chinese-utils就可以
> > > 
> > > 
> > > 具体要怎么操作啊
> > 
> > 
> > 把chinese-utils-1.0.jar移动到tachidesk安装目录下的jre\lib\ext里就可以
> 
> 我是docker安装的tachidesk 好像没找到你说的安装目录。。。

可能是需要找到docker中的jre路径

**Comment by 2Loong6** [comment]
写了一个兼容项目，仅供参考：https://github.com/2Loong6/tachidesk-copymanga-compatible

**Comment by stevenyomi** [comment]
已在下载页上传 Tachidesk 兼容版插件，删除了“繁体转简体”、“登录状态下搜索”、“章末吐槽页”功能。

**Comment by eventhorizonsky** [comment]
作者的Tachidesk版本会出现无法搜索的问题，完美的解法应该还是下载chinese-utils-1.0.jar到程序的jre\lib\ext目录并重启，然后安装tachiyomi版插件，不过章末吐槽页似乎无法正常加载，其他都正常

**Comment by stevenyomi** [comment]
> 作者的Tachidesk版本会出现无法搜索的问题

已替换上传修复版。

**Comment by OpenGG** [comment]
https://github.com/OpenGG/docker-tachidesk-chinese
