### ISSUE TITLE
1.3.46版本更新速率过快，被网站block

### ISSUE THREAD

**Issue by 362516282** [stevenyomi/copymanga#25]
在1.3.45版本，三台设备上测试，在网络良好的情况下，每分钟更新的数量最高为14个，超过该该数量则会被阻止。
目前的最新版本1.3.46出现了被阻止的情况，但被阻止的时间均为1秒，可以考虑更改一下更新速率吗？

**Comment by 362516282** [comment]
或将调整更新速率的功能恢复

**Comment by stevenyomi** [comment]
已了解，稍后更新调整。

**Comment by stevenyomi** [comment]
已更新 v1.3.47。
