### ISSUE TITLE
“其他系列”问题

### ISSUE THREAD

**Issue by AzureGu** [stevenyomi/copymanga#26]
在拷贝漫画上，有些（我迄今为止遇到的所有带有“其他系列”的）漫画正常连载顺序会被归类在“其他系列”里，而“连载（xx话）”的是莫名其妙时期的剧情。能不能给一个选项屏蔽连载，只看“其他系列”。
![IMG_20221224_221608](https://user-images.githubusercontent.com/96013345/209439664-58707bf3-3cee-43b1-89e5-94b71d7bb346.jpg)
![IMG_20221224_221454](https://user-images.githubusercontent.com/96013345/209439675-6245a40e-fb60-46be-a819-1a50415ced33.jpg)
![IMG_20221224_221130](https://user-images.githubusercontent.com/96013345/209439680-e95ef14d-3763-466c-a4c1-9d99d8dc8f45.jpg)

**Comment by zhongfly** [comment]
拷贝网站的问题，请自己打开拷贝漫画的相应网页，它们在拷贝上面就是被分到其他系列

每次看未读章节不就好了
而且这些漫画动漫之家和拷贝是一样的内容吧，又不存在打码之类的事，用动漫之家就好了

**Comment by stevenyomi** [comment]
发帖者可能认为点进去之后不方便翻阅目录，这个选项容易做，稍后更新。

**Comment by stevenyomi** [comment]
已更新 v1.3.48。

**Comment by AzureGu** [comment]
> 拷贝网站的问题，请自己打开拷贝漫画的相应网页，它们在拷贝上面就是被分到其他系列
> 
> 每次看未读章节不就好了 而且这些漫画动漫之家和拷贝是一样的内容吧，又不存在打码之类的事，用动漫之家就好了

实用主义者不懂完美主义者看到错乱排版的痛😰

**Comment by AzureGu** [comment]
半夜更新 开发者辛苦了😆
