### ISSUE TITLE
更新被阻止问题

### ISSUE THREAD

**Issue by 362516282** [stevenyomi/copymanga#27]
可能由于copymanga策略变化，出现了大量被阻止的项目，建议恢复将自主选择更新速度的功能，以免后续由于此问题的麻烦。
使用版本为1.3.47
![Uploading Screenshot_20221226_181328_com.estrongs.android.pop.jpg…]()

**Comment by stevenyomi** [comment]
无法复现，你的截图也没传上来。

**Comment by 362516282** [comment]
![Screenshot_20221226_181328_com estrongs android pop](https://user-images.githubusercontent.com/36665073/209803423-f6c2ba77-8fc5-4649-aa76-e0d6362bee87.jpg)

**Comment by stevenyomi** [comment]
你现在再检查一次，还能复现吗？记得检查一下插件版本。

**Comment by 362516282** [comment]
![mmexport1672227366295](https://user-images.githubusercontent.com/36665073/209806195-528e3776-9c80-43e1-b160-89686cb850ed.jpg)
![Screenshot_20221228_193535_com estrongs android pop](https://user-images.githubusercontent.com/36665073/209806214-ba171df9-b411-433c-aced-ca27345114.jpg)
两个设备进行测试，漫画数量相同，一个错误60条，一个错误53条。版本均为1.3.47

**Comment by 362516282** [comment]
![Screenshot_20221228_193535_com estrongs android pop](https://user-images.githubusercontent.com/36665073/209806592-9e982792-904e-4ad1-82b3-aa166332b36b.jpg)

**Comment by stevenyomi** [comment]
https://www.lanzout.com/ilrtK0jla5ij

你试试这个，我微调了一下限速。安装之后打开 app 直接检查一次更新。如果还是有报错，进高级设置导出崩溃日志上传到这里。

**Comment by 362516282** [comment]
[tachiyomi_crash_logs.txt](https://github.com/stevenyomi/copymanga/files/10314485/tachiyomi_crash_logs.txt)
失败101个项目

**Comment by 362516282** [comment]
[tachiyomi_crash_logs(1).txt](https://github.com/stevenyomi/copymanga/files/10314504/tachiyomi_crash_logs.1.txt)
另一台设备失败76个

**Comment by stevenyomi** [comment]
你好像确实被严格限流了（大概是 1 分钟 6 次），可能是检查更新太多了，我把选项加回来吧。

另外确认一下，你是否在设置 - 书架里开启了“自动刷新元数据”选项？

**Comment by 362516282** [comment]
默认开着没动，确实偶尔可以全部更新

**Comment by 362516282** [comment]
不更新元数据影响会小一点吗？
一般这种限流会持续多久呢？

**Comment by stevenyomi** [comment]
> 不更新元数据影响会小一点吗？

这个不影响，我只是看你的日志确认一下。（PS：这个选项默认是关闭的）

> 一般这种限流会持续多久呢？

不知道，正常访问一般都是 15 次/分钟，你这个 6 次/分钟看起来有点异常，目前只能手调。如果之后遇到这个情况比较多的话可以考虑做一个自动检测。

**Comment by stevenyomi** [comment]
已更新 v1.3.48。
