### ISSUE TITLE
可以问一下拷贝漫画是怎么识别到tachiyomi吗？

### ISSUE THREAD

**Issue by blass0009** [stevenyomi/copymanga#3]
关注了这个问题几天，也看了一些之前的issues，但是本人并不懂技术，不太能理解之前的讨论。
抱歉占用了您的时间，烦请能否为我通俗易懂的解释一下拷贝漫画到底是如何识别到tachiyomi，以及插件为何不能一劳永逸的欺骗网站，必须两者不断的搞猫鼠游戏

关于UA，之前您提到

> 关于 User Agent：这里用什么他们就封，所以我就改用最新版 Chrome 的 User Agent，结果他们还真就封了，这下用浏览器的用户也没法访问了。目前可以在插件设置里面改版本号。我应该直接用设备自己的 User Agent，或者随机一下，这样每个设备都不一样。

意思是拷贝漫画的网站人员，在监视插件的默认UA，然后封掉这个UA是吗？还是说他们有什么检测手段能够知道某一具体UA是被插件所使用的？

> I made a little research myself, and found that CopyManga seems to be detecting Tachiyomi by checking the "referer" http header.
In a request to the chapter api, for example [this](https://api.copymanga.info/api/v3/comic/yishiyuzhimo/chapter/41ac26bc-8124-11ec-a557-024352452ce0)
If "referer" is set to "https://www.copymanga.org/", then it returns special image for Tachiyomi
If "referer" is any other value, or even not set, then it returns normal image

这位说的大概是网站会检测一个Referer对吧，插件有办法伪造这个Referer吗？说到底插件的Referer不可以模拟成和浏览器的Referer一模一样，然后一劳永逸吗？

**Comment by KoSChicken** [comment]
监视UA现在意义不大了，毕竟可以自己改。不过看上去他们希望用户都能去用他们自己的APP所以一直在投入精力去阻止第三方形式的访问。我只能说且用且珍惜，尽量把能找到替代源的漫画都迁移到别的源或者改用官方APP。
最后还是感谢steven的继续维护。

**Comment by stevenyomi** [comment]
因为插件的访问总有一定的特征（不一定局限于 UA 和 Referer）并且难以做到完全随机无法预测，网站只需要找到特征并且屏蔽就可以了。这只是比较基本的手段。此 Issue 稍后删除。
