### ISSUE TITLE
无法在浏览-图源处搜索漫画

### ISSUE THREAD

**Issue by corvo007** [stevenyomi/copymanga#33]
无法在浏览-图源处搜索漫画，会一直显示在加载中（图1，但是直接点进源可以看到能加载出漫画（图2）
![IMG_20230313_002732](https://user-images.githubusercontent.com/67192165/224558565-51538b3d-9e9e-4629-bf16-4db52b234cb4.jpg)
![Screenshot_2023-03-13-00-27-05-369_eu kanade tachiyomi](https://user-images.githubusercontent.com/67192165/224558566-8eac1150-bbd0-4fdb-ad7f-958bf2d32457.jpg)

**Comment by star2056** [comment]
我不是开发者，但我遇到过与你基本相同的问题，我也是无法在图源搜索漫画，应用会卡死，但是点进图源可以看到漫画总览
我的解决办法是更新了我自己设备的webview版本，因为很多应用对于低版本的webview已经不支持了。
也许这个办法可以帮到你

**Comment by stevenyomi** [comment]
如楼上所说，应该是因为 WebView 版本太低，理论上你这样在图源里面搜漫画也是搜不出来的。（麻烦确认一下）

可以在设置里面关闭“在登录状态下搜索漫画”开关。

**Comment by isudfv** [comment]
我也是这个问题，play里更新webview之后就可以了

**Comment by stevenyomi** [comment]
已更新 v1.4.50，默认关闭“在登录状态下搜索漫画”开关，如需此功能可手动打开。
