### ISSUE TITLE
contaction reset

### ISSUE THREAD

**Issue by RX93CN** [stevenyomi/copymanga#34]
最近拷贝漫画的网站在部分地区被劫持，除非挂加速器，基本都无法连接，但是拷贝漫画柜app更新到2.0.2后，可以无视劫持连接，拷贝插件是不是能根据这个更新一下。
![Screenshot_2023-03-14-13-07-46-857_eu kanade tachiyomi](https://user-images.githubusercontent.com/110704357/224903948-878ef3a3-703e-43f5-87a2-0e37219103f0.jpg)

**Comment by stevenyomi** [comment]
网址已经更新过，如果后续再有发生的话重新开 Issue。
