### ISSUE TITLE
在书架页面无法更新

### ISSUE THREAD

**Issue by suguruosako** [stevenyomi/copymanga#35]
如题，书架页面下拉刷新和全局更新都获取不到最新的。（已经是看过的漫画，不是被跳过更新的）只有点进去下拉才能更新。（官方源就没有这个问题）

**Comment by stevenyomi** [comment]
无法复现，应该是你的设置的问题。看看漫画是不是没有看完，有未读的默认也是跳过的。读完再检查更新。
