### ISSUE TITLE
拷贝漫画显示加载失败

### ISSUE THREAD

**Issue by KuanKan410** [stevenyomi/copymanga#36]
今天开始，即使挂了梯子也显示漫画加载失败，没有日志信息，换了API域名也没有用
![Screenshot_2023-03-24-09-17-49-59_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/73146120/227400046-bacb0d82-8b51-47f4-8624-ac62cdf0b312.jpg)

**Comment by 15ovo** [comment]
节点问题 换梯子
