### ISSUE TITLE
希望大佬能优化下漫画详情页点击作者的搜索功能

### ISSUE THREAD

**Issue by zddgitee** [stevenyomi/copymanga#40]
1.目前看来是直接调用的全局搜索
类似 xxx.site/search?q=(作者名)&q_type= 是模糊搜索范围结果过于庞大，
哪怕点箭头进入二级页面筛选为仅仅搜索作者也是模糊范围
xxx.site/search?q=(作者名)q_type=author结果还是太多要一个个甄别
希望能像网页一样，使用作者的独一匹配关键字母进行搜索
xxx.site/author/（独一匹配关键字母）/comics就能精准找到作者名下漫画
2.多个作者无法分开搜索，就无法分别查看各自作品

**Comment by stevenyomi** [comment]
目前 Tachiyomi 的 API 结构还不能方便地储存额外数据，所以你说的作者代码存不下来；多个作者搜索也不是插件能解决的事情。
