### ISSUE TITLE
能否将下载的api从webp改为jpg

### ISSUE THREAD

**Issue by yushizui** [stevenyomi/copymanga#43]
应该就是改个后缀的事，下载下来的文件体积更小，兼容性更友好

**Comment by stevenyomi** [comment]
> 下载下来的文件体积更小

WebP 是压缩率更高的图片格式，JPG 更大。

> 兼容性更友好

Tachiyomi 完全支持 WebP。如果你需要下载到其他地方看，请使用其他工具。
