### ISSUE TITLE
官方版到0.14.6，为什么修改版一直都是0.13.6 ？

### ISSUE THREAD

**Issue by firegl99** [stevenyomi/copymanga#45]
如题，是官方版的0.14.6有什么问题，所以修改版一直没有跟进更新吗？

**Comment by stevenyomi** [comment]
0.14.x 是用 Compose 重写的，bug 会比较多，界面美化和性能欠佳，新功能没有我特别急需的，因此没有更新。

如果你需要的话我可以做一个 0.14.6 的 ghproxy 修改版。

**Comment by firegl99** [comment]
多谢大佬回复。我也没有特别需要新版本的功能，只是有点好奇。
