### ISSUE TITLE
[Question] 修改版是做什么的？

### ISSUE THREAD

**Issue by f0rdream** [stevenyomi/copymanga#47]
Release里除了插件apk，还有关于修改版apk的下载。

没有找到相关的说明，在下载页面找到了gh proxy相关的字样，猜测是对于github墙的绕过?

希望可以解答一下。

By the way, great work bro, thanks for all your effort.

**Comment by stevenyomi** [comment]
下载页面上面有说明。

> ghproxy 修改版不能与官方对应版本共存，作用是在国内网络环境中顺利连接 GitHub，插件有更新时能第一时间检测到，没有其他修改。ghproxy.2 版增加了 1.4 版插件支持，修复 MIUI 插件安装问题，修复了一个 bug，更新了界面文字。

版本停留在 0.13.6 的原因在 #45 解释了。
