### ISSUE TITLE
9.1 0时起显示加载失败

### ISSUE THREAD

**Issue by azurezcr** [stevenyomi/copymanga#48]
更换节点与网址均无效。
是否可能与拷贝漫画关闭旧版访问有关？

**Comment by zouquan741** [comment]
+1

**Comment by Danehy** [comment]
+1

**Comment by zxzxm** [comment]
+1

**Comment by RX93CN** [comment]
拷贝的app已经提示旧版将永久停止维护，如果插件用的是旧版的端口，那就直接无法使用

**Comment by kevin930321** [comment]
還有救嗎

**Comment by RX93CN** [comment]
> 還有救嗎
插件目前没办法用，等修复。如果想要用，要么下载拷贝的app，要么用tachiyomi的vomic插件，这个能搜到大部分copymanga的漫画，除了需要登录的

**Comment by AzureGu** [comment]
蹲一个修复🥀 在国内当二次元怎么这么难啊🥀

**Comment by anklcaptain** [comment]
正看着呢忽然就什么都加载不出了，好难

**Comment by anklcaptain** [comment]
> > 還有救嗎
> > 插件目前没办法用，等修复。如果想要用，要么下载拷贝的app，要么用tachiyomi的vomic插件，这个能搜到大部分copymanga的漫画，除了需要登录的

请问这个vomic插件你现在能打开吗，我再tachiyomi和浏览器中都加载不了

**Comment by RX93CN** [comment]
> > > 還有救嗎
> > > 插件目前没办法用，等修复。如果想要用，要么下载拷贝的app，要么用tachiyomi的vomic插件，这个能搜到大部分copymanga的漫画，除了需要登录的
> 
> 请问这个vomic插件你现在能打开吗，我再tachiyomi和浏览器中都加载不了

插件设置里改域名，默认的那个有问题，改成数字的那个

**Comment by anklcaptain** [comment]
> > > > 還有救嗎
> > > > 插件目前没办法用，等修复。如果想要用，要么下载拷贝的app，要么用tachiyomi的vomic插件，这个能搜到大部分copymanga的漫画，除了需要登录的
> > 
> > 
> > 请问这个vomic插件你现在能打开吗，我再tachiyomi和浏览器中都加载不了
> 
> 插件设置里改域名，默认的那个有问题，改成数字的那个

改成数字确实可以了，感谢！

**Comment by taiyisama** [comment]
没有呀

**Comment by wwwssxd** [comment]
> > > > > 還有救嗎
> > > > > 插件目前没办法用，等修复。如果想要用，要么下载拷贝的app，要么用tachiyomi的vomic插件，这个能搜到大部分copymanga的漫画，除了需要登录的
> > > 
> > > 
> > > 请问这个vomic插件你现在能打开吗，我再tachiyomi和浏览器中都加载不了
> > 
> > 插件设置里改域名，默认的那个有问题，改成数字的那个
> 
> 改成数字确实可以了，感谢！

请问插件设置在哪呀？

**Comment by wwwssxd** [comment]
> > > > > 還有救嗎
> > > > > 插件目前没办法用，等修复。如果想要用，要么下载拷贝的app，要么用tachiyomi的vomic插件，这个能搜到大部分copymanga的漫画，除了需要登录的
> > > 
> > > 
> > > 请问这个vomic插件你现在能打开吗，我再tachiyomi和浏览器中都加载不了
> > 
> > 插件设置里改域名，默认的那个有问题，改成数字的那个
> 
> 改成数字确实可以了，感谢！

没有数字的啊，几个域名还都是英文

**Comment by RX93CN** [comment]
> > > > > > 還有救嗎
> > > > > > 插件目前没办法用，等修复。如果想要用，要么下载拷贝的app，要么用tachiyomi的vomic插件，这个能搜到大部分copymanga的漫画，除了需要登录的
> > > > 
> > > > 
> > > > 请问这个vomic插件你现在能打开吗，我再tachiyomi和浏览器中都加载不了
> > > 
> > > 
> > > 插件设置里改域名，默认的那个有问题，改成数字的那个
> > 
> > 
> > 改成数字确实可以了，感谢！
> 
> 没有数字的啊，几个域名还都是英文

不是copymanga，是另外的插件vomic

**Comment by anklcaptain** [comment]
> > > > > > > 還有救嗎
> > > > > > > 插件目前没办法用，等修复。如果想要用，要么下载拷贝的app，要么用tachiyomi的vomic插件，这个能搜到大部分copymanga的漫画，除了需要登录的
> > > > > 
> > > > > 
> > > > > 请问这个vomic插件你现在能打开吗，我再tachiyomi和浏览器中都加载不了
> > > > 
> > > > 
> > > > 插件设置里改域名，默认的那个有问题，改成数字的那个
> > > 
> > > 
> > > 改成数字确实可以了，感谢！
> > 
> > 
> > 没有数字的啊，几个域名还都是英文
> 
> 不是copymanga，是另外的插件vomic

现在数字那个网站好像也不好使了

**Comment by RX93CN** [comment]
> > > > > > > > 還有救嗎
> > > > > > > > 插件目前没办法用，等修复。如果想要用，要么下载拷贝的app，要么用tachiyomi的vomic插件，这个能搜到大部分copymanga的漫画，除了需要登录的
> > > > > > 
> > > > > > 
> > > > > > 请问这个vomic插件你现在能打开吗，我再tachiyomi和浏览器中都加载不了
> > > > > 
> > > > > 
> > > > > 插件设置里改域名，默认的那个有问题，改成数字的那个
> > > > 
> > > > 
> > > > 改成数字确实可以了，感谢！
> > > 
> > > 
> > > 没有数字的啊，几个域名还都是英文
> > 
> > 
> > 不是copymanga，是另外的插件vomic
> 
> 现在数字那个网站好像也不好使了

![Screenshot_2023-09-02-15-35-20-450_eu kanade tachiyomi](https://github.com/stevenyomi/copymanga/assets/110704357/94276fdb-3996-4142-bcb8-da79dfa8e4d3)
网站被攻击，等待修复。

**Comment by YaegakiOwl** [comment]
拷贝挂了之后，居然又透过vomic的源看拷贝的源

**Comment by stevenyomi** [comment]
已更新 v1.4.52。
