### ISSUE TITLE
用的Tachiyomi 8.31晚开始就提示加载失败 9.1下午重试还不行

### ISSUE THREAD

**Issue by gankumangcao** [stevenyomi/copymanga#49]
拷贝插件是最新版，Tachiyomi官方版

**Comment by zxzxm** [comment]
#48

**Comment by lantisky** [comment]
应该是拷贝漫画的域名改了, 发现是.tv

**Comment by wwwssxd** [comment]
我也用不了了

**Comment by wwwssxd** [comment]
奇怪的是为什么安卓平板看不了，安卓手机却能看？都是同样的版本

**Comment by anklcaptain** [comment]
> 奇怪的是为什么安卓平板看不了，安卓手机却能看？都是同样的版本

你的安卓手机现在还可以吗

**Comment by Berserk46** [comment]
昨天晚上还能看，今早起来就不行了。作者大大会修复吗

**Comment by fnkgtr** [comment]
用不到

**Comment by wwwssxd** [comment]
> > 奇怪的是为什么安卓平板看不了，安卓手机却能看？都是同样的版本
> 
> 你的安卓手机现在还可以吗

安卓手机在设置-高级-插件里选那个长的英文的就可以了，但是安卓平板没有这个，不知道为啥

**Comment by kevin930321** [comment]
> > > 奇怪的是为什么安卓平板看不了，安卓手机却能看？都是同样的版本
> > 
> > 你的安卓手机现在还可以吗
> 
> 安卓手机在设置-高级-插件里选那个长的英文的就可以了，但是安卓平板没有这个，不知道为啥

長的英文?packageinstaller那個嗎，那個不是只是安裝用的方法而已嗎?

**Comment by anklcaptain** [comment]
> > > 奇怪的是为什么安卓平板看不了，安卓手机却能看？都是同样的版本
> > 
> > 
> > 你的安卓手机现在还可以吗
> 
> 安卓手机在设置-高级-插件里选那个长的英文的就可以了，但是安卓平板没有这个，不知道为啥

请问长的英文是哪一个选项啊

**Comment by wwwssxd** [comment]
> > > > 奇怪的是为什么安卓平板看不了，安卓手机却能看？都是同样的版本
> > > 
> > > 你的安卓手机现在还可以吗
> > 
> > 安卓手机在设置-高级-插件里选那个长的英文的就可以了，但是安卓平板没有这个，不知道为啥
> 
> 長的英文?packageinstaller那個嗎，那個不是只是安裝用的方法而已嗎?

其实我也搞不懂为啥我的手机能用，但我看平板和手机设置的不同的地方也只有这一个了

**Comment by kevin930321** [comment]
> > > > > 奇怪的是为什么安卓平板看不了，安卓手机却能看？都是同样的版本
> > > > 
> > > > 你的安卓手机现在还可以吗
> > > 
> > > 安卓手机在设置-高级-插件里选那个长的英文的就可以了，但是安卓平板没有这个，不知道为啥
> > 
> > 長的英文?packageinstaller那個嗎，那個不是只是安裝用的方法而已嗎?
> 
> 其实我也搞不懂为啥我的手机能用，但我看平板和手机设置的不同的地方也只有这一个了

你的域名是用哪個啊?

**Comment by stevenyomi** [comment]
Duplicate of #48
