### ISSUE TITLE
参数错误

### ISSUE THREAD

**Issue by MisakaOne** [stevenyomi/copymanga#5]
![Screenshot_2022-07-03-12-27-00-423_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/108571772/177032287-75bd5b7a-0d2e-4a19-a0e7-dc168472a6ff.jpg)
![Screenshot_2022-07-03-12-32-54-572_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/108571772/177032295-753a9730-e24d-4683-ad9d-6109ba203808.jpg)
ua：Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by stevenyomi** [comment]
更换域名。

**Comment by MisakaOne** [comment]
已更新1.3.34 切换域名没有效果 依然参数错误

**Comment by stevenyomi** [comment]
> 已更新1.3.34 切换域名没有效果 依然参数错误

已更新 1.3.35。
