### ISSUE TITLE
想問為何無官方版

### ISSUE THREAD

**Issue by NeKoOuO** [stevenyomi/copymanga#52]
偶然得知有這個插件 想說在官方app上搜不到 是為什麼沒有官方版？

**Comment by ouovouo** [comment]
[#12376](https://github.com/tachiyomiorg/tachiyomi-extensions/pull/12376)
[REMOVED_SOURCES](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md)

**Comment by NeKoOuO** [comment]
>thx
