### ISSUE TITLE
似乎從今日（ 2023/10/12 ）開始，部分圖片無法正常載入

### ISSUE THREAD

**Issue by ximellon** [stevenyomi/copymanga#53]
如標題所述，今日注意到有此問題。

並非僅單一作品出現，各個作品的各章節都有極高機率出現，且重新嘗試載入並無任何幫助。目前處於完全無法正常閱讀之狀況。

奇怪的是，提供 API 更新的 @fumiama 所作的 app 依舊能夠正常載入圖片，但似乎解析度較低（僅以肉眼主觀判斷，並無實證）？

**Comment by chris7395328** [comment]
同样遇到就这个情况，一开始长期把画质设置到最低800正常用了一会儿，后来全部不行，隔一段时间看了几页就全部载入失败

**Comment by ximellon** [comment]
剛剛嘗試了一下，發現似乎沒問題了。所以可能是伺服器那邊的問題吧？

**Comment by Ruoyin-Haku** [comment]
我这边试了一下之前出问题的章节都可以正常阅读了 应该是服务端那边的问题
