### ISSUE TITLE
吐槽页无法加载或下载

### ISSUE THREAD

**Issue by YaegakiOwl** [stevenyomi/copymanga#56]
当下载时，如果打开吐槽页，那么最后一页将无法下载，一直卡在22/23之类，但在关闭吐槽页之后就能下载了，以下为下载失败后显示的英文（只能在通知栏查看，点进去之后是下载中心，所以未能完全显示）：kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at

**Comment by YaegakiOwl** [comment]
在线同样无法加载吐槽页

**Comment by YaegakiOwl** [comment]
使用的是原版tachiyomi，并非修改版

**Comment by stevenyomi** [comment]
请提供是哪个漫画，哪一章节。另外请在 app 高级设置中分享崩溃日志，上传到这里。

**Comment by YaegakiOwl** [comment]
> 请提供是哪个漫画，哪一章节。另外请在应用程序高级设置中分享崩溃日志，上传到这里。

尝试的所有漫画都无法加载，目录为（杀人狂转生现代单亲妈妈所有章节，异世界默示录所有章节，邻家小魔女第五话，连环杀手降临异世界第13，14话，骷髅领主没能守住副本第269话）

错误日志中的TXT文件内容为：
App version: 0.14.7-6171 (standard, 69223df27, 108, 2023-11-04T21:07Z)
Android version: 13 (SDK 33; build TKQ1.221114.001 test-keys)
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: cmi (cmi)
Device model: Mi 10 Pro
WebView: Android System WebView 117.0.5938.156

Problematic extensions:
- CopyManga
  Installed: 1.4.52 / Available: ?
  Obsolete: false / Unofficial: true

--------- beginning of main
11-07 01:02:17.519  9905  9905 E tachiyomi.debug: Not starting debugger since process cannot load the jdwp agent.
11-07 01:02:17.787  9905 10001 E chromium: [1107/010217.786811:ERROR:variations_seed_loader.cc(37)] Seed missing signature.
11-07 01:02:18.021  9905  9962 E libEGL  : pre_cache appList: ,,
11-07 01:02:18.058  9905 10028 E SQLiteLog: (284) automatic index on C(manga_id)
11-07 01:02:18.058  9905 10028 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
11-07 01:02:18.392  9905  9962 E LB      : fail to open node: No such file or directory
11-07 01:02:18.394  9905  9962 E perf_hint: Session creation failed, mPreferredRateNanos: -1

**Comment by Vicious-circIe** [comment]
所有漫画所有章节都无法加载
[tachiyomi_crash_logs.txt](https://github.com/stevenyomi/copymanga/files/13613409/tachiyomi_crash_logs.txt)

**Comment by Steve-337** [comment]
加载吐槽页的api现在是500错误了

**Comment by Steve-337** [comment]
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 0: Expected start of the object '{', but had '' instead at path: $ JSON input: �����NG�_�ګ�b�|�|�>D.....

~~不太懂这方面，稍微看了一下，这是没有对gzip压缩过的内容进行解压缩就直接读取了吗?~~

**Comment by Steve-337** [comment]
> kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 0: Expected start of the object '{', but had '' instead at path: $ JSON input: �����NG�_�ګ�b�|�|�>D.....
> 
> ~~不太懂这方面，稍微看了一下，这是没有对gzip压缩过的内容进行解压缩就直接读取了吗?~~

找到解决方法了，把请求的accept-encoding值删了就行了(或者做个gzip解压)

**Comment by stevenyomi** [comment]
那 dmzj 也是同样的问题咯？但 gzip 不是 OkHttp 本就支持的吗，为什么会没解压呢，我看类似的 https://github.com/keiyoushi/extensions-source/pull/65 是 brotli 的问题。

**Comment by Steve-337** [comment]
> 那 dmzj 也是同样的问题咯？但 gzip 不是 OkHttp 本就支持的吗，为什么会没解压呢，我看类似的 https://github.com/keiyoushi/extensions-source/pull/65 是 brotli 的问题。

我不太懂这方面，只是通过简单的抓包和看下载报错好像是gzip没解压的问题?，抓包重写删掉accept-encoding请求后获取到的是未压缩数据，吐槽页也正常加载和下载了。具体为什么gzip没有解压那就看大佬您能不能找出原因了，小白只能做到这一步😂

**Comment by Steve-337** [comment]
> > 那 dmzj 也是同样的问题咯？但 gzip 不是 OkHttp 本就支持的吗，为什么会没解压呢，我看类似的 https://github.com/keiyoushi/extensions-source/pull/65 是 brotli 的问题。
> 
> 我不太懂这方面，只是通过简单的抓包和看下载报错好像是gzip没解压的问题，抓包重写删掉accept-encoding请求后获取到的是未压缩数据，吐槽页也正常加载和下载了。
具体为什么gzip没有解压那就看大佬您能不能找出原因了，小白只能做到这一步😂

**Comment by Steve-337** [comment]
> 那 dmzj 也是同样的问题咯？但 gzip 不是 OkHttp 本就支持的吗，为什么会没解压呢，我看类似的 https://github.com/keiyoushi/extensions-source/pull/65 是 brotli 的问题。

我看这个修改中，加了一个
val headers = request.headers.newBuilder() 
    .removeAll("Accept-Encoding") 
    .build() 
来删掉请求中的Accept-Encoding

**Comment by Steve-337** [comment]
> 那 dmzj 也是同样的问题咯？但 gzip 不是 OkHttp 本就支持的吗，为什么会没解压呢，我看类似的 https://github.com/keiyoushi/extensions-source/pull/65 是 brotli 的问题。

我看了一下dmzj的请求，虽然请求中有accept-encoding: br,gzip，但服务器返回的是未压缩数据

**Comment by stevenyomi** [comment]
查出来是 app 的 bug，已提交 PR https://github.com/tachiyomiorg/tachiyomi/pull/10388

**Comment by stevenyomi** [comment]
已更新 v1.4.53。
