### ISSUE TITLE
部分漫画无法正常加载目录

### ISSUE THREAD

**Issue by 2607627233** [stevenyomi/copymanga#58]
![Screenshot_20231120-152859](https://github.com/stevenyomi/copymanga/assets/43110396/399fb74c-2d4e-4594-b496-8fe7d1edbfe8)
![Screenshot_20231120-152812](https://github.com/stevenyomi/copymanga/assets/43110396/bab1b3c2-647c-4247-b858-cbebb96bc031)
![Screenshot_20231120-152827](https://github.com/stevenyomi/copymanga/assets/43110396/d5721c5d-1e8f-439c-ba8a-f2a19b5faa09)
安卓x86平板

**Comment by stevenyomi** [comment]
无法复现。
