### ISSUE TITLE
更新到最新的1.3.35还是无法浏览，报错如下

### ISSUE THREAD

**Issue by moonking2020** [stevenyomi/copymanga#6]
能麻烦大神看看嘛？![image](https://user-images.githubusercontent.com/66074695/177241793-a255b896-6d8b-4d61-8ece-cc3616e6667f.png)
另外那个UA是要打什么一直没搞懂，我IOS上用那个连接出来的如下：Mozilla/5.0 (iPhone; CPU iPhone OS 13_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Mobile/15E148 Safari/604.1是要打这么一长串？

**Comment by stevenyomi** [comment]
自身网络问题，非插件问题，请检查是否有开启任何代理工具。

**Comment by moonking2020** [comment]
非常感谢，已经搞定，确实开了翻墙，开启设置里的海外线路就好了
