### ISSUE TITLE
大佬，快快漫画3挂了

### ISSUE THREAD

**Issue by ZerOri** [stevenyomi/copymanga#60]
RT，特来提醒

**Comment by stevenyomi** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/19411

**Comment by hsiayuchih** [comment]
看这个问题是几周前反馈的了，但是官方那边好像没有要修复的意思

**Comment by ZerOri** [comment]
> 看这个问题是几周前反馈的了，但是官方那边好像没有要修复的意思

tachiyomi那边也反馈了，只能等了，至少作者没说要放弃……
如果这个图源不做了确实挺可惜的，我60部哔哩哔哩图源，损失惨重

**Comment by stevenyomi** [comment]
这个源大概率只有我在维护，不过我暂时还没空，过几天可能可以看看。另外，这个源本身不算稳定维护的那种，很可能会有一天关闭，建议做好准备。

**Comment by ZerOri** [comment]
> 这个源大概率只有我在维护，不过我暂时还没空，过几天可能可以看看。另外，这个源本身不算稳定维护的那种，很可能会有一天关闭，建议做好准备。

感谢，不知能否提供图源维护方面的协助

**Comment by hsiayuchih** [comment]
> 这个源大概率只有我在维护，不过我暂时还没空，过几天可能可以看看。另外，这个源本身不算稳定维护的那种，很可能会有一天关闭，建议做好准备。

大佬厉害啊，原来这个源也是您维护的呀

**Comment by hsiayuchih** [comment]
> > 看这个问题是几周前反馈的了，但是官方那边好像没有要修复的意思
> 
> tachiyomi那边也反馈了，只能等了，至少作者没说要放弃…… 如果这个图源不做了确实挺可惜的，我60部哔哩哔哩图源，损失惨重

啥情况？我刚刚发现扩展的项目疑是删掉了？！

**Comment by ZerOri** [comment]
> > > 看这个问题是几周前反馈的了，但是官方那边好像没有要修复的意思
> > 
> > 
> > tachiyomi那边也反馈了，只能等了，至少作者没说要放弃…… 如果这个图源不做了确实挺可惜的，我60部哔哩哔哩图源，损失惨重
> 
> 啥情况？我刚刚发现扩展的项目疑是删掉了？！

从 V0.15.0 起 Tachiyomi 修改了插件库策略，改为手动添加插件库URL的方式，设置路径为「设置>浏览>插件仓库>添加」，此后官方插件库成为历史。官方说明：[插件列表已移除](https://tachiyomi.org/news/2024-01-09-extensions-removal)
目前找到的一个可用的仓库URL：**https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json**

**Comment by ZerOri** [comment]
> > > > 看这个问题是几周前反馈的了，但是官方那边好像没有要修复的意思
> > > 
> > > 
> > > tachiyomi那边也反馈了，只能等了，至少作者没说要放弃…… 如果这个图源不做了确实挺可惜的，我60部哔哩哔哩图源，损失惨重
> > 
> > 
> > 啥情况？我刚刚发现扩展的项目疑是删掉了？！
> 
> 从 V0.15.0 起 Tachiyomi 修改了插件库策略，改为手动添加插件库URL的方式，设置路径为「设置>浏览>插件仓库>添加」，此后官方插件库成为历史。
官方声明：https://tachiyomi.org/news/2024-01-09-extensions-removal

**Comment by hsiayuchih** [comment]
> > > > 看这个问题是几周前反馈的了，但是官方那边好像没有要修复的意思
> > > 
> > > 
> > > tachiyomi那边也反馈了，只能等了，至少作者没说要放弃…… 如果这个图源不做了确实挺可惜的，我60部哔哩哔哩图源，损失惨重
> > 
> > 
> > 啥情况？我刚刚发现扩展的项目疑是删掉了？！
> 
> 从 V0.15.0 起 Tachiyomi 修改了插件库策略，改为手动添加插件库URL的方式，设置路径为「设置>浏览>插件仓库>添加」，此后官方插件库成为历史。官方说明：[插件列表已移除](https://tachiyomi.org/news/2024-01-09-extensions-removal) 目前找到的一个可用的仓库URL：**https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json**

感谢，不过我目前用的还是分支J2K，看了下还没更新。不知道后续更新会不会也移除掉

**Comment by hsiayuchih** [comment]
> > > > > 看这个问题是几周前反馈的了，但是官方那边好像没有要修复的意思
> > > > 
> > > > 
> > > > tachiyomi那边也反馈了，只能等了，至少作者没说要放弃…… 如果这个图源不做了确实挺可惜的，我60部哔哩哔哩图源，损失惨重
> > > 
> > > 
> > > 啥情况？我刚刚发现扩展的项目疑是删掉了？！
> > 
> > 
> > 从 V0.15.0 起 Tachiyomi 修改了插件库策略，改为手动添加插件库URL的方式，设置路径为「设置>浏览>插件仓库>添加」，此后官方插件库成为历史。官方说明：[插件列表已移除](https://tachiyomi.org/news/2024-01-09-extensions-removal) 目前找到的一个可用的仓库URL：**https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json**
> 
> 感谢，不过我目前用的还是分支J2K，看了下还没更新。不知道后续更新会不会也移除掉。话说你这个是怎么找到的？

**Comment by ZerOri** [comment]
> > > > > 看这个问题是几周前反馈的了，但是官方那边好像没有要修复的意思
> > > > 
> > > > 
> > > > tachiyomi那边也反馈了，只能等了，至少作者没说要放弃…… 如果这个图源不做了确实挺可惜的，我60部哔哩哔哩图源，损失惨重
> > > 
> > > 
> > > 啥情况？我刚刚发现扩展的项目疑是删掉了？！
> > 
> > 
> > 从 V0.15.0 起 Tachiyomi 修改了插件库策略，改为手动添加插件库URL的方式，设置路径为「设置>浏览>插件仓库>添加」，此后官方插件库成为历史。官方说明：[插件列表已移除](https://tachiyomi.org/news/2024-01-09-extensions-removal) 目前找到的一个可用的仓库URL：**https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json**
> 
> 感谢，不过我目前用的还是分支J2K，看了下还没更新。不知道后续更新会不会也移除掉

J2K分支共用tachiyomi的插件库，一样的。当然，不排除作者自建插件库。目前最大的问题还是后续插件的更新维护，缺少一个集中反馈和维护的仓库

**Comment by hsiayuchih** [comment]
> > > > > > 看这个问题是几周前反馈的了，但是官方那边好像没有要修复的意思
> > > > > 
> > > > > 
> > > > > tachiyomi那边也反馈了，只能等了，至少作者没说要放弃…… 如果这个图源不做了确实挺可惜的，我60部哔哩哔哩图源，损失惨重
> > > > 
> > > > 
> > > > 啥情况？我刚刚发现扩展的项目疑是删掉了？！
> > > 
> > > 
> > > 从 V0.15.0 起 Tachiyomi 修改了插件库策略，改为手动添加插件库URL的方式，设置路径为「设置>浏览>插件仓库>添加」，此后官方插件库成为历史。官方说明：[插件列表已移除](https://tachiyomi.org/news/2024-01-09-extensions-removal) 目前找到的一个可用的仓库URL：**https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json**
> > 
> > 
> > 感谢，不过我目前用的还是分支J2K，看了下还没更新。不知道后续更新会不会也移除掉
> 
> J2K分支共用tachiyomi的插件库，一样的。当然，不排除作者自建插件库。目前最大的问题还是后续插件的更新维护，缺少一个集中反馈和维护的仓库

确实，我刚刚看在线的插件列表已经加载不出来了。我这边也找到的一个可用的仓库URL：https://[raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json](https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json)
