### ISSUE TITLE
提示：新版Tachiyomi(0.15.0+)上信任问题

### ISSUE THREAD

**Issue by Steve-337** [stevenyomi/copymanga#61]
更新新版tachiyomi(0.15.0)后，每次重启APP都需要再次点击信任
从0.15.2开始，变成每次更新插件后需要重新点击信任
(更新后可能需要重启APP才能正常点击信任，否则会一直卡在下载中/仍然提示更新，即便插件已经下载安装成功。）
(对于其他曾经是官方的插件：如无法安装则需要卸载旧版插件或使用核心破解，因为新维护的插件与以前官方的签名不一致)

**Comment by stevenyomi** [comment]
https://github.com/tachiyomiorg/tachiyomi/issues/10290
