### ISSUE TITLE
无法正常更新漫画

### ISSUE THREAD

**Issue by Ruoyin-Haku** [stevenyomi/copymanga#62]
![Screenshot_2024-01-07-01-10-50-010_eu kanade tachiyomi](https://github.com/stevenyomi/copymanga/assets/72408548/ffc73613-5952-4ffa-b3f5-2fe09fb76037)
用tachiyomi自带的webview连接提示超时
![Screenshot_2024-01-07-01-11-03-957_com android chrome](https://github.com/stevenyomi/copymanga/assets/72408548/6639d023-514e-426b-9eb8-f5efbe19b88f)
用chrome可以正常访问

**Comment by stevenyomi** [comment]
API 出错，属于常见现象，晚点再试。PC 版页面没有走 API。
