### ISSUE TITLE
0.15版本tachiyomi导致已下载章节不标注已下载

### ISSUE THREAD

**Issue by histion** [stevenyomi/copymanga#63]
![Screenshot_2024-01-07-16-13-07-286_eu kanade tachiyomi](https://github.com/stevenyomi/copymanga/assets/65994410/74f98261-d0c8-4d02-a027-42fa9e0b834e)
如果点击下载会在文件夹内下载一个名为:章节（1）的重复文件，然后才会被标注已下载。

**Comment by Steve-337** [comment]
正确选择文件夹与迁移文件后去设置-高级-清除下载索引就行了

**Comment by histion** [comment]
> 正确选择文件夹与迁移文件后去设置-高级-清除下载索引就行了

确实可以了，感谢
