### ISSUE TITLE
添加热辣漫画支持

### ISSUE THREAD

**Issue by Xeonzilla** [stevenyomi/copymanga#64]
原本是打算在Tachiyomi官方下请求的，但是看到官方不再维护拷贝漫画，大概率也不会接纳这个请求，于是想到在这里开一个issue。如果打扰到了开发者真是万分抱歉。

最近在使用拷贝漫画这一漫画源时总是会超时/连接失败，并且通过排查这与我的网络环境无关，只能是拷贝漫画服务器的问题了。在网上冲浪偶然发现了[“热辣漫画”](https://github.com/hotmanga/hotmangaSite)，并且热辣漫画的Github主页有一个拷贝漫画的链接，热辣漫画的样式和拷贝漫画也极其相似，基本可以确定它们师出同门。唯一的不同是在拷贝漫画阵亡的时候，热辣漫画的服务仍然正常。

据我观察此插件设置里有一项“API域名”，或许直接添加热辣漫画的API就可以正常工作了？

**Comment by stevenyomi** [comment]
这个网站基本需要付费吧，需求也不大，暂不考虑支持。
