### ISSUE TITLE
無法正常添加至倉庫

### ISSUE THREAD

**Issue by NeKoOuO** [stevenyomi/copymanga#65]
![Screenshot_2024-01-08-14-38-14-498_eu.kanade.tachiyomi.sy.jpg](https://github.com/stevenyomi/copymanga/assets/111511925/5771a075-7b73-4cd0-a05e-0cf339f77fff)
圖上是SY的添加倉庫的功能
![Screenshot_2024-01-08-14-35-21-686_eu.kanade.tachiyomi.sy.jpg](https://github.com/stevenyomi/copymanga/assets/111511925/d0030850-d05d-4cd2-a6bd-560ebce6841c)
但是這個倉庫卻沒有辦法正常使用
![Screenshot_2024-01-08-14-38-22-687_eu.kanade.tachiyomi.sy.jpg](https://github.com/stevenyomi/copymanga/assets/111511925/4fb50c87-9f69-4437-86c7-c259d5d8c10c)
會導致整個倉庫爆掉連原本的插件庫都偵測不到（第一個非官方的可以用beerpiss/tachiyomi-unofficial-extensions）

**Comment by stevenyomi** [comment]
SY 只支持 repo 分支，我稍后修改一下。

**Comment by NeKoOuO** [comment]
> SY 只支持 repo 分支，我稍后修改一下。

好的感謝您

**Comment by stevenyomi** [comment]
修改好了。

**Comment by hsiayuchih** [comment]
感谢分享，又发现了个新的漫画扩展

**Comment by NeKoOuO** [comment]
> 感谢分享，又发现了个新的漫画扩展

不客氣😄
