### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by WSZZJ1** [stevenyomi/copymanga#66]
0.15.0一下载就暂停，点继续也没反应

**Comment by WSZZJ1** [comment]
原版tachiyomi,点下载按钮一直在转圈，在下载队列里点继续也没有用

**Comment by stevenyomi** [comment]
https://github.com/stevenyomi/copymanga/issues/63#issuecomment-1880038113

**Comment by WSZZJ1** [comment]
还是不行，在最后一页状态栏提示kotlinx.serialization.json.internal.JsonDeco
dingException: Unexpected JSON token a...

**Comment by stevenyomi** [comment]
不下载直接看那一章会报错吗？另外麻烦在设置 - 高级里面分享崩溃日志，然后传上来。

**Comment by WSZZJ1** [comment]
关闭章末吐槽页之后好了，谢谢

**Comment by stevenyomi** [comment]
Duplicate of #56
