### ISSUE TITLE
能否添加喵上漫画源的支持

### ISSUE THREAD

**Issue by hsiayuchih** [stevenyomi/copymanga#67]
www.miaoshangmanhua.com
谢谢大佬了！
另外想问下大佬，如果自己尝试制作漫画源的话具体需要进行些什么步骤呢？

**Comment by stevenyomi** [comment]
漫画源去 https://github.com/keiyoushi/extensions-source 提。

自己想做可以参考 https://github.com/tachiyomiorg/extensions 官方仓库，里面的 CONTRIBUTING.md 有教程。

**Comment by hsiayuchih** [comment]
好的，感谢大佬
