### ISSUE TITLE
章末留言無法正常下載

### ISSUE THREAD

**Issue by NeKoOuO** [stevenyomi/copymanga#68]
![Screenshot_2024-01-11-09-25-52-953_eu.kanade.tachiyomi.sy.jpg](https://github.com/stevenyomi/copymanga/assets/111511925/c988e8a1-e0cf-4932-8f3f-dd7ffc85ec2c)
如圖![Screenshot_2024-01-11-09-28-52-901_eu.kanade.tachiyomi.sy.jpg](https://github.com/stevenyomi/copymanga/assets/111511925/7c5a6e20-f4e1-4233-82d7-3366d73eafc9)
下載完後最後的留言加載不出來導致卡在最後一張無法完成下載

**Comment by stevenyomi** [comment]
Duplicate of #56

**Comment by NeKoOuO** [comment]
用fork 的怎麼辦 等更新有辦法搜到推送嗎？

**Comment by stevenyomi** [comment]
我刚好准备更新一下插件，稍后就发。

**Comment by NeKoOuO** [comment]
> 我刚好准备更新一下插件，稍后就发。

好的感謝

**Comment by stevenyomi** [comment]
已更新 v1.4.53。
