### ISSUE TITLE
1.4.53版本提示无法加载该图片

### ISSUE THREAD

**Issue by 362516282** [stevenyomi/copymanga#69]
tachiyomi版本0.15.2
插件版本1.4.53
漫画内容提示无法加载该图片，点击“在webview中打开”，图片可以正常显示

**Comment by 362516282** [comment]
且无法下载
随机选择一部分漫画均存在该问题
[tachiyomi_crash_logs.txt](https://github.com/stevenyomi/copymanga/files/13909609/tachiyomi_crash_logs.txt)
![Screenshot_2024-01-12-07-47-14-855_eu kanade tachiyomi](https://github.com/stevenyomi/copymanga/assets/36665073/18fd857e-90ea-4f7f-b474-7e0c64698ec1)
![Uploading Screenshot_2024-01-12-07-47-19-246_eu.kanade.tachiyomi.jpg…]()

**Comment by 362516282** [comment]
![Screenshot_2024-01-12-07-49-11-421_com android browser](https://github.com/stevenyomi/copymanga/assets/36665073/a43b38dc-8816-4602-9861-8b1260e4a67d)
下载失败提示

**Comment by stevenyomi** [comment]
NXDOMAIN 是网络问题啊，不像是插件问题。再观察看看。你也可以回退到上一个版本看看是不是也会出错。

**Comment by 362516282** [comment]
退回1.4.52也不行
主要这边在webview里看是正常的，到软件里就不行，应该不是网络问题

**Comment by stlion** [comment]
> NXDOMAIN 是网络问题啊，不像是插件问题。再观察看看。你也可以回退到上一个版本看看是不是也会出错。

我卸载53版安装52版上去，还是出现同样的状况。更早时候甚至点“在webview中打开”都不能显示图片，不知是不是拷贝漫画那边的问题。
PS：有个题外问题，我填入源之后，有提示拷贝漫画有插件更新，不过点击后只下载没成功安装（我用shizuku），高级里换其他安装器选项，点安装时提示包解析错误云云，不知为何。我现在只能手工下载、安装、信任。

**Comment by TomaYoshitaka** [comment]
升级1.4.53后出现同样问题，webview显示net:ERR_CONNECTION_CLOSED
以为可以通过重新登录解决但是从webview进拷贝漫画网站一直卡在logo界面
![Screenshot_2024-01-12-09-40-05-924_eu kanade tachiyomi](https://github.com/stevenyomi/copymanga/assets/7340168/4c901b96-2f5e-4d1d-958b-40d940f74220)
![Screenshot_2024-01-12-09-40-24-254_eu kanade tachiyomi](https://github.com/stevenyomi/copymanga/assets/7340168/18c495ff-e26b-4dec-8681-9a4839c7eef3)
![Screenshot_2024-01-12-09-39-52-110_eu kanade tachiyomi-edit](https://github.com/stevenyomi/copymanga/assets/7340168/47839d5c-32d7-4aa4-8883-a7557c0ba675)

**Comment by 362516282** [comment]
@TomaYoshitaka webview打都不开应该是你选择域名的问题了，默认的.com没问题

**Comment by TomaYoshitaka** [comment]
> @TomaYoshitaka webview打都不开应该是你选择域名的问题了，默认的.com没问题

并不是，经测试API域名里所有域名选项都试了，都是图片无法打开、webview卡logo，但同时不影响加载列表和列表内搜索，第一次见到
![Screenshot_2024-01-12-09-55-00-050_eu kanade tachiyomi-edit](https://github.com/stevenyomi/copymanga/assets/7340168/84dc661a-74f3-4b63-bd3f-0fffdd220503)

**Comment by zacred0rryn** [comment]
是否与上游 (拷贝漫画网站) 有关？

我使用的是 `1.4.52` 插件，今日凌晨时能正常使用，上午发现无法使用。我查看了我使用的代理应用的日志发现拷贝漫画的部分 CDN 域名 (例如 `hi77-overseas.mangafunb.fun`) 经过 Cloudflare DoH 的解析出错，导致无法载图。

我使用 PC 浏览器尝试在拷贝漫画网页阅读漫画，发现部分 CDN 能够正常运作 (例如 `hi77-overseas.mangafuna.xyz`)；而使用 `hi77-overseas.mangafunb.fun` 进行图片分发时则与插件一样无法载图，日志显示的内容与 Android 端一致。

---

更新 1 (CST 12:22 AM)

[测试](https://www.whatsmydns.net/#A/hi77-overseas.mangafunb.fun)发现，部分地区的 A 记录解析结果比较稳定。我尝试在代理软件配置中添加 DNS 规则，使该解析有问题的域名通过 `fakeip` 发送至远端 (我测试时选择了德国节点)，发现可以成功与该域名建立连接，可以载图。

---
更新 2 (CST 12:33 AM)

根据我的设备的表现，使用上似乎已经恢复正常。

**Comment by TomaYoshitaka** [comment]
> 升级1.4.53后出现同样问题，webview显示net:ERR_CONNECTION_CLOSED 以为可以通过重新登录解决但是从webview进拷贝漫画网站一直卡在logo界面 ![Screenshot_2024-01-12-09-40-05-924_eu kanade tachiyomi](https://private-user-images.githubusercontent.com/7340168/296101533-4c901b96-2f5e-4d1d-958b-40d940f74220.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDI3OTUsIm5iZiI6MTcwNTA0MjQ5NSwicGF0aCI6Ii83MzQwMTY4LzI5NjEwMTUzMy00YzkwMWI5Ni0yZjVlLTRkMWQtOTU4Yi00MGQ5NDBmNzQyMjAuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMDY1NDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGMyN2IxYjQ4YTdlODMxNGFkNDExMjA5ZmZlYjViNmJjMWZiYWIwM2VjOGE5MDE2YjA5OGE4NjIyMDNlNTFlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ifccL2wgBbZrDmldPrru-9nw4ahgCzWjSejKzlw2dBE) ![Screenshot_2024-01-12-09-40-24-254_eu kanade tachiyomi](https://private-user-images.githubusercontent.com/7340168/296101549-18c495ff-e26b-4dec-8681-9a4839c7eef3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDI3OTUsIm5iZiI6MTcwNTA0MjQ5NSwicGF0aCI6Ii83MzQwMTY4LzI5NjEwMTU0OS0xOGM0OTVmZi1lMjZiLTRkZWMtODY4MS05YTQ4MzljN2VlZjMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMDY1NDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQxOWI4YWVjNDYyZTNiZDIxM2NiYjgyNjg4OTFiYTIwZWExMWE3ODRkMDM5MjYyZjM5MWQyOTIwNjlkOGJiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gWJmG-zXE-Ax3xAEeUB8qRQhi3MJFvK1kxlMNaOOc1E) ![Screenshot_2024-01-12-09-39-52-110_eu kanade tachiyomi-edit](https://private-user-images.githubusercontent.com/7340168/296101565-47839d5c-32d7-4aa4-8883-a7557c0ba675.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDI3OTUsIm5iZiI6MTcwNTA0MjQ5NSwicGF0aCI6Ii83MzQwMTY4LzI5NjEwMTU2NS00NzgzOWQ1Yy0zMmQ3LTRhYTQtODg4My1hNzU1N2MwYmE2NzUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMDY1NDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjBhZDdkNjJhMTNhN2U4NWM0YjA2N2M0ZDRlZTgxMTJmYzc0NWE5ZWIyYWQ3OTQ5ODA5Zjk1OTNmOTIxZGU4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UAwZMWE4ebe1cQQxPcZjWiC6Qm-JqYoSo0-0Qy5wLcY)

目前测试回复正常，应该只是临时性的网络问题
