### ISSUE TITLE
頁碼有錯位

### ISSUE THREAD

**Issue by lemonkimi** [stevenyomi/copymanga#7]
現在是使用1.3.37，發現漫畫順序與實際不一致，配置並無更改過，希望大大有空能解決一下

**Comment by stevenyomi** [comment]
请提供具体作品、章节，以及插件设置。另外请与网页版对照复核是否确实错页。

**Comment by lemonkimi** [comment]
這裡是設置圖，希望不影響大大看。
然後我有去看大概是10頁以後就有錯位，常看的都有這個問題，圖例是尾頁到了11頁。
感謝大大的幫助。

stevenyomi ***@***.***> 於 2022年7月12日 週二 上午8:29 寫道：

**Comment by stevenyomi** [comment]
> 這裡是設置圖，希望不影響大大看。

你用邮件回复的看不到图片。

**Comment by stevenyomi** [comment]
另外请尝试 设置→高级→清除图片缓存，然后重新查看章节，并与网页版对照。

**Comment by lemonkimi** [comment]
不好意思，現在可以了嗎，我清除緩存後錯位依舊存在，雖然位置變了
![Screenshot_20220712-200229_Tachiyomi.png](https://user-images.githubusercontent.com/79898040/178485854-a5b01756-40a1-40ad-86d8-efcaf0ed18ee.png)
![Screenshot_20220712-200221_Tachiyomi.png](https://user-images.githubusercontent.com/79898040/178485874-15026fce-83f4-4546-bc6f-319b67ebe98f.png)
![Screenshot_20220712-200216_Tachiyomi.png](https://user-images.githubusercontent.com/79898040/178485901-2194b5b4-3b69-449a-80aa-b0e8b6547f82.png)
![Screenshot_20220712-200207_Tachiyomi.png](https://user-images.githubusercontent.com/79898040/178485931-3d03bfc5-477e-4500-a1dc-0f9987cb4468.png)
![Screenshot_20220712-200408_Tachiyomi.png](https://user-images.githubusercontent.com/79898040/178485948-065f0991-5c29-4623-a7d5-67862b380df9.png)

**Comment by stevenyomi** [comment]
你使用的是另一个插件 CopyMangas（末尾多一个 s，而且是旧版本），请卸载之后从 Releases 下载最新的 1.3.37 安装。
