### ISSUE TITLE
频繁提示Failed to fetch available extensions

### ISSUE THREAD

**Issue by hsiayuchih** [stevenyomi/copymanga#72]
想问下大佬，频繁提示这个是什么原因？是没开科学上网的原因吗？有办法关闭相关选项让他不提示吗？尝试过关闭自动更新之类的选项但还是会频繁提示

**Comment by stevenyomi** [comment]
使用最新版 Tachiyomi v0.15.3。

**Comment by hsiayuchih** [comment]
> 使用最新版 Tachiyomi v0.15.3。

我用的是分支JK，且已经是最新版的了

**Comment by stevenyomi** [comment]
Duplicate of https://github.com/Jays2Kings/tachiyomiJ2K/issues/1756
