### ISSUE TITLE
能不能增加章节分组功能

### ISSUE THREAD

**Issue by Diluka** [stevenyomi/copymanga#76]
拷贝漫画的章节是分组的，比如单行本，连载，同人等。但是这个插件目前丢失了分组信息，所有章节混在一起了

**Comment by stevenyomi** [comment]
章节名称已有标注。Tachi 并不支持章节分组功能。

**Comment by Diluka** [comment]
那插件本身也没法开发针对某一部的设置进行章节过滤？也就是不需要UI支持，直接数据过滤
