### ISSUE TITLE
你好，请问Suwayomi无法抓取到目录页需要怎么解决？

### ISSUE THREAD

**Issue by aimeidaer** [stevenyomi/copymanga#78]
从tachiyomi导入的备份包，属于拷贝漫画的都可以正常观看和搜索目录页，但是使用网页端拷贝漫画图源进行搜索，只能抓取到封面和数据，但是无法加载出目录页和实际内容，安卓端提示为404，请问各位大神有什么办法解决吗？

**Comment by RockStarBAD** [comment]
我也遇到这个问题。。。最后解决了吗
