### ISSUE TITLE
小白请教，这个怎么在tachiyomi中使用？

### ISSUE THREAD

**Issue by ashengaashenga** [stevenyomi/copymanga#79]
下载之后应该怎么在tachiyomi运行？

**Comment by Young-Lord** [comment]
首先下载安装Mihon或Tachiyomi和这个插件，完成Mihon或Tachiyomi初始化
然后看图
![IMG_20240711_151659](https://github.com/stevenyomi/copymanga/assets/51789698/160eb869-8fa8-4793-a741-e735cdb9015b)
![Screenshot_2024-07-11-15-14-15-005_app mihon-edit](https://github.com/stevenyomi/copymanga/assets/51789698/af6c7434-1270-4d55-a946-ca4e81b5dc9d)
![Screenshot_2024-07-11-15-15-07-286_app mihon-edit](https://github.com/stevenyomi/copymanga/assets/51789698/c0674854-3eb5-4eb8-ab86-d03f5d0b6f91)
![Screenshot_2024-07-11-15-15-27-945_app mihon-edit](https://github.com/stevenyomi/copymanga/assets/51789698/a7a0fd3c-7446-4a22-b446-99f47dac1836)
![Screenshot_2024-07-11-15-16-04-426_app mihon-edit](https://github.com/stevenyomi/copymanga/assets/51789698/ae685a8c-4505-4b6f-b9c9-f65e3ad477cf)
接着直接搜索、加书架就行了

**Comment by ashengaashenga** [comment]
> 首先下载安装Mihon或Tachiyomi和这个插件，完成Mihon或Tachiyomi初始化 然后看图 ![IMG_20240711_151659](https://private-user-images.githubusercontent.com/51789698/347719353-160eb869-8fa8-4793-a741-e735cdb9015b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODI4OTksIm5iZiI6MTcyMDY4MjU5OSwicGF0aCI6Ii81MTc4OTY5OC8zNDc3MTkzNTMtMTYwZWI4NjktOGZhOC00NzkzLWE3NDEtZTczNWNkYjkwMTViLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA3MjMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ZWJjOTY0MjQxMzczZTQxY2VmNzI0NTk1NzY0Nzg0YjI4OWE4NDhmOWIxNGMyMWFhNDczYmE4YWMwMDViNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vo8yThO7x_mFGxeAq4a74WcuURopfiHXoMU7xq6AhHo) ![Screenshot_2024-07-11-15-14-15-005_app mihon-edit](https://private-user-images.githubusercontent.com/51789698/347718667-af6c7434-1270-4d55-a946-ca4e81b5dc9d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODI4OTksIm5iZiI6MTcyMDY4MjU5OSwicGF0aCI6Ii81MTc4OTY5OC8zNDc3MTg2NjctYWY2Yzc0MzQtMTI3MC00ZDU1LWE5NDYtY2E0ZTgxYjVkYzlkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA3MjMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYzU3ODVhOTE3YjNlYzIxMTFkN2EzMjZjMjQ5ZjEyN2M5ZGM5ZWVmMWU1MDVhM2ZlMjYyNmQ1Njk3ZTdmMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AO9U-rdGi839uOQPS5U1QO8uDPeYXZsiUhuCxjmyboc) ![Screenshot_2024-07-11-15-15-07-286_app mihon-edit](https://private-user-images.githubusercontent.com/51789698/347718684-c0674854-3eb5-4eb8-ab86-d03f5d0b6f91.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODI4OTksIm5iZiI6MTcyMDY4MjU5OSwicGF0aCI6Ii81MTc4OTY5OC8zNDc3MTg2ODQtYzA2NzQ4NTQtM2ViNS00ZWI4LWFiODYtZDAzZjVkMGI2ZjkxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA3MjMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ODQyNzdkMTcxZTA3ZDUzNzA0NDRhMjc1N2E2YTgwM2RhMjI0ZDZiODRkYTZkOTRhZmIwOTg4OTZjOTNmYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WUJzSmo4w3XPNSfsBhz8rUfFK0Fz78OMpR20XPTB4r8) ![Screenshot_2024-07-11-15-15-27-945_app mihon-edit](https://private-user-images.githubusercontent.com/51789698/347718697-a7a0fd3c-7446-4a22-b446-99f47dac1836.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODI4OTksIm5iZiI6MTcyMDY4MjU5OSwicGF0aCI6Ii81MTc4OTY5OC8zNDc3MTg2OTctYTdhMGZkM2MtNzQ0Ni00YTIyLWI0NDYtOTlmNDdkYWMxODM2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA3MjMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ODc0ZjhlNDJmOGY1YzhiNjBiYWU4NTY0MDVlMGE3ODhjY2YwNmQ3ZWJiYzZjNjA2N2QwOWU5OGZkY2NkMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dIBs58_myjyKbaAnYW0rzrx0bBtTuWX5zimAhMQu9g8) ![Screenshot_2024-07-11-15-16-04-426_app mihon-edit](https://private-user-images.githubusercontent.com/51789698/347718703-ae685a8c-4505-4b6f-b9c9-f65e3ad477cf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODI4OTksIm5iZiI6MTcyMDY4MjU5OSwicGF0aCI6Ii81MTc4OTY5OC8zNDc3MTg3MDMtYWU2ODVhOGMtNDUwNS00YjZmLWI5YzktZjY1ZTNhZDQ3N2NmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA3MjMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZDUzYzQ2NjA2MzdhOTkxYTMyYTZlMjczY2JkMTk1ZGZmYzhkODI5ZWU5ZWQ2ZTJhMmZhNDNlOGZiMjlhZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QRyBEyCHfQoZYTAOvWPOqz1IOfIrTpSqnL6AFrQFJ9I) 接着直接搜索、加书架就行了

感谢，已解决问题

**Comment by Young-Lord** [comment]
那就 close issue

**Comment by ashengaashenga** [comment]
Thx
