### ISSUE TITLE
请问能否PR到别的项目中（非本人）？

### ISSUE THREAD

**Issue by whylalacantuse** [stevenyomi/copymanga#80]
RT，keiyoushi/extensions-source中数量多而且似乎能保持维护...

**Comment by Steve-337** [comment]
之所以单独维护是因为之前在官方库里面的时候被拷贝漫画官方盯上了(鬼图贴脸)，所以你的想法基本不太可能
而且你应该也能发现此仓库并没有插件源码，应该是闭源的(~~大概~~)

**Comment by whylalacantuse** [comment]
> 之所以单独维护是因为之前在官方库里面的时候被拷贝漫画官方盯上了(鬼图贴脸)，所以你的想法基本不太可能 而且你应该也能发现此仓库并没有插件源码，应该是闭源的(~大概~)
哦哦，明白了。谢谢你。
