### ISSUE TITLE
Tachidesk所有作品无法获取目录 Cache data may be lost when replacing the meta field of a MangaType object.

### ISSUE THREAD

**Issue by gsxgmpkt9020** [stevenyomi/copymanga#83]
[127.0.0.1-1727019836155.log](https://github.com/user-attachments/files/17090259/127.0.0.1-1727019836155.log)

![image](https://github.com/user-attachments/assets/d542e865-c95e-4972-ad80-ba4ed7f101f1)

Server
Suwayomi-Server Preview

Server version
v1.1.1-r1599

**Comment by stevenyomi** [comment]
请将 issue 提交给 Tachidesk (Suwayomi)。
