### ISSUE TITLE
最近好像有点卡

### ISSUE THREAD

**Issue by MCER2020** [stevenyomi/copymanga#9]
挂梯子和不挂都试了，有时候能加载出来看，但是加载新章节很卡，有时候直接加载不出来提示502，甚至拷贝漫画的那个主搜寻页面都进不去了，是最近他们又查到了吗？

**Comment by stevenyomi** [comment]
不是，是站点自身问题。可以尝试在不同时间/换用不同梯子节点。之后会更新版本支持新的域名，但是对 app 内的连接情况可能没有太多改善。
